# Generated by Django 4.1.7 on 2023-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
